services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: count_collab
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d count_collab']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - count-collab

volumes:
  postgres_data:

networks:
  count-collab:
    driver: bridge
